kind: Service
apiVersion: v1
metadata:
  name: atsea-shop-frontend
spec:
  type: NodePort
  selector:
    app: atsea-shop
  ports:
  - protocol: TCP
    port: 8080
    nodePort: 8080

---

apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: atsea-shop-frontend-deployment
  labels:
    app: atsea-shop
spec:
  replicas: 2
  selector:
    matchLabels:
      app: atsea-shop
  template:
    metadata:
      labels:
        app: atsea-shop
    spec:
      containers:
      - name: atsea-shop
        image: $frontendregistry:latest
        ports:
        - containerPort: 8080
